services:
  web:
    build: .
    image: flask:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1  # Enables debugging mode in Flask
      - DATABASE_URL=postgresql://eklavya:test123@db:5432/expenses_db
      - PYTHONPATH=/expense_manager
    volumes:
      - .:/expense_manager
    depends_on:
      - db
    
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=eklavya
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=expenses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eklavya -d expenses_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  postgres_data:
